### ISSUE TITLE
There has been a critical error on this website.

### ISSUE THREAD

**Issue by asen0v** [markusbegerow/Wp-Adv-Quiz#44] opened 2023-10-31 12:38 UTC
Hello, 
When I add the short-code to my new created page it's showing me "There has been a critical error on this website. - [Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/) " . 

Any ideas how to fix this?

**Comment by markusbegerow** [comment] 2023-11-01 08:29
Hey @asen0v.
which version did you use? Did you refresh your cache? I tested it on a clean wordpress environment andmit works.
I look forward to your feedback

**Comment by keithfun** [comment] 2023-11-01 10:07
Hi @markusbegerow,
Version 1.0.2 was used, cache was taken care of as well. Are there any compatibility issues with any other wp plugins that you might be aware of?

**Comment by markusbegerow** [comment] 2023-11-01 12:15
So,

actual test settings on my dev: WordPress 6.3.2 clean.
Both ways - shortcode and gutenberg-block - works

Gutenberg & shortcode:
![image](https://github.com/markusbegerow/Wp-Adv-Quiz/assets/44146279/ec6c2849-0a0e-4c78-a2d4-db43d9dd7324)

Live:
![image](https://github.com/markusbegerow/Wp-Adv-Quiz/assets/44146279/d2c9e1ad-0e81-4db1-a992-c0c5c2f96e8d)

Please recduce step by step of using wp plugins or please provide more information.

**Comment by keithfun** [comment] 2023-11-01 12:29
Hi, @markusbegerow. The site is running Elementor as a builder therefore I am inclined to think that might trigger this error. Curious to know what you think? Easiest way to test it would probably be to do a backup and then deactivate Elementor.

**Comment by markusbegerow** [comment] 2023-11-03 11:34
@keithfun this could be a problem. I will test it with elementor. Which version do you use?

**Comment by keithfun** [comment] 2023-11-04 10:14
Hi, @markusbegerow sorry for the late reply. Version 3.17.2

**Comment by markusbegerow** [comment] 2023-11-04 18:16
So, I've just tested it. Here is the result:

![image](https://github.com/markusbegerow/Wp-Adv-Quiz/assets/44146279/12c6824c-dcf9-4ae5-90a1-35bdfa233177)

Please do a deep dive analysis on your own.

The problem is not our lovely WP-Adv-Quiz.
I will close the issue. 

When you have new information, we can continue again...

**Closed by markusbegerow** 2023-11-04 18:16 UTC

**Comment by keithfun** [comment] 2023-11-07 10:21
Hi, @markusbegerow and for anyone else wondering it was the Master addons for elementor plugin that had to be deactivated. Hope it saves someone else the hustle.
